export default {
  ALB: 'Albania',
  ARE: 'United Arab Emirates',
  ARG: 'Argentina',
  ARM: 'Armenia',
  AUS: 'Australia',
  AZE: 'Azerbaijan',
  BEL: 'Belgium',
  BEN: 'Benin',
  BGR: 'Bulgaria',
  BIH: 'Bosnia And Herzegovina',
  BLR: 'Belarus',
  BMU: 'Bermuda',
  BRN: 'Brunei Darussalam',
  CAN: 'Canada',
  CHE: 'Switzerland',
  CHL: 'Chile',
  CHN: 'China',
  CIV: 'Côte D`ivoire/Ivory Coast',
  CMR: 'Cameroon',
  CYM: 'Cayman Islands',
  CZE: 'Czech Republic',
  DEU: 'Germany',
  DNK: 'Denmark',
  EGY: 'Egypt',
  ESP: 'Spain',
  EST: 'Estonia',
  FIN: 'Finland',
  FRA: 'France',
  GBR: 'United Kingdom',
  GEO: 'Georgia',
  GIB: 'Gibraltar',
  GRC: 'Greece',
  HKG: 'Hong Kong',
  HRV: 'Croatia',
  HUN: 'Hungary',
  IDN: 'Indonesia',
  IND: 'India',
  IRL: 'Ireland',
  IRN: 'Iran, Islamic Republic Of',
  ISL: 'Iceland',
  ISR: 'Israel',
  ITA: 'Italy',
  KAZ: 'Kazakstan',
  KGZ: 'Kyrgyzstan',
  LIE: 'Liechtenstein',
  LTU: 'Lithuania',
  LUX: 'Luxembourg',
  LVA: 'Latvia',
  MAR: 'Morocco',
  MCO: 'Monaco',
  MDA: 'Moldova, Republic Of',
  MEX: 'Mexico',
  MYS: 'Malaysia',
  NLD: 'Netherlands',
  NOR: 'Norway',
  NZL: 'New Zealand',
  OMN: 'Oman',
  PAK: 'Pakistan',
  POL: 'Poland',
  PRI: 'Puerto Rico',
  PRT: 'Portugal',
  PSE: 'Palestine',
  QAT: 'Qatar',
  ROU: 'Romania',
  RUS: 'Russian Federation',
  SGP: 'Singapore',
  SVK: 'Slovakia',
  SWE: 'Sweden',
  TJK: 'Tajikistan',
  TKM: 'Turkmenistan',
  TUR: 'Turkey',
  UKR: 'Ukraine',
  USA: 'United States',
  UZB: 'Uzbekistan',
  VEN: 'Venezuela',
  ZAF: 'South Africa'
};
